collections:
  tour:
    output: true
    permalink: /tour/:path/

  happyUser:
    output: true
    permalink: /happyUser/:path/ 
  
  gallery:
    output: true
    permalink: /gallery/:path/   

  gobi:
    output: true
    permalink: /gobi/:path/       

  defaults:
  - scope:
      path: "assets/img"
    values:
      image: true  